### ISSUE TITLE
Cannot convert spp model by darknet2Caffe

### ISSUE THREAD

**Issue by stereomatchingkiss** [dog-qiuqiu/MobileNetv2-YOLOV3#12]
OS : ubuntu18.04

Follow the instructions, install and build the caffe, able to convert nano, lite, the error messages are

```
Traceback (most recent call last):
  File "darknet2caffe.py", line 443, in <module>
    darknet2caffe(cfgfile, weightfile, protofile, caffemodel)
  File "darknet2caffe.py", line 8, in darknet2caffe
    net_info = cfg2prototxt(cfgfile)
  File "darknet2caffe.py", line 309, in cfg2prototxt
    bottom2 = topnames[prev_layer_id2]
KeyError: 126

```

**Comment by dog-qiuqiu** [comment]
你是否修改过模型的cfg，还是直接转我的模型报错？

**Comment by stereomatchingkiss** [comment]
> 
> 
> 你是否修改过模型的cfg，是否直接转我提供的模型报的错吗？

是的，直接转换，没有修改过cfg
